### ISSUE TITLE
动画速度bug

### ISSUE THREAD

**Issue by Soulize** [qqlittleice/MiuiHome#105]
在MIUIhome模块中设定动画速度不为1时，动画不断重复播放时速度会叠加。如1.2的动画速度会调整MIUI动画至一个比原版稍慢的速度，但反复切后台后，速度会不断叠加到非常慢，前台任务会以非常慢的速度移动至后台多任务界面中。

**Comment by Soulize** [comment]
![Uploading 3bdea9a151acbe6136ec9ede8366380b.gif…]()

**Comment by Soulize** [comment]
![3bdea9a151acbe6136ec9ede8366380b](https://user-images.githubusercontent.com/63684394/157869664-21b747bc-0524-4641-8971-07bc23c928f9.gif)

**Comment by YuKongA** [comment]
已知

**Comment by YuKongA** [comment]
已解决
