### ISSUE TITLE
face this :android.os.DeadSystemException

### ISSUE THREAD

**Issue by JonyWinner** [qqlittleice/MiuiHome#73]
When the module is.loading by lsp,it gives this and my lsp not work after build,and give shell crash error
![Uploading Screenshot_2021-12-05-02-22-13-990_bin.mt.plus.jpg…]()

**Comment by 1767523953** [comment]
Sorry, I can't see the screenshot. Have you uploaded it fully?

**Comment by JonyWinner** [comment]
![Screenshot_2021-12-05-02-22-13-990_bin mt plus](https://user-images.githubusercontent.com/63949560/144731482-77e1ff86-a698-43b0-82a6-2ab84dba283c.jpg)


> Sorry, I can't see the screenshot. Have you uploaded it fully?

Here sir
