### ISSUE TITLE
MIUI12.5 布局只有10x10没有更大选项

### ISSUE THREAD

**Issue by tyjavajar** [qqlittleice/MiuiHome#82]
![IMG_20211225_200529](https://user-images.githubusercontent.com/38398992/147399218-9835ce22-eb3b-4013-83d8-4f51ff971dc6.jpg)
请问开发者是bug还是使用方法问题？

**Comment by YuKongA** [comment]
你没救了，洗洗睡吧(下CI

**Comment by tyjavajar** [comment]
> 你没救了，洗洗睡吧(下CI

谢谢，找到了，只会在GH下release找东西，这次受教了😀
